knu/main/urls.py
from django.urls import path
from . import views

app_name = 'main'   # 앱을 구분할 필요 없으면 안적어도 됨 
urlpatterns = [
    path('', views.index, name='index'),
    path('sum/', views.sum, name='sum'),
    path('problem2/', views.problem2, name='problem2'),
    path('problem3/', views.problem3, name='problem3'),
    path('problem4/', views.problem4, name='problem4'),
]

knu/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('accounts/',include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('main/', include("main.urls")),   #PJT url에서 app의 url로 
    path('mypolls/', include("mypolls.urls")),
    path('<int:user_pk>/password/', views.change_password, name='change_password' )
]

knu/mypolls/urls.py
from django.urls import path
from .views import survey, result

app_name = 'mypolls'
urlpatterns = [
    path('survey/', survey, name='survey'),
    path('result/', result, name='result'),
]

knu/mypolls/models.py
from django.db import models


AGE_CHOICES = [
    ('20-24', '20~24세'),
    ('25-29', '25~29세'),
    ('30-34', '30~34세'),
    ('35-39', '35~39세'),
    ('40-44', '40~44세'),
    ('45-49', '45~49세'),
    ('50-54', '50~54세'),
    ('55-59', '55~59세'),
    ('60+', '60세 이상'),
]

GENDER_CHOICES = [
    ('male', '남성'),
    ('female', '여성'),
    ('other', '기타'),
]

FINANCIAL_GOAL_CHOICES = [
    ('savings', '적금'),
    ('investment', '투자'),
    ('retirement', '은퇴 준비'),
    ('education', '교육 자금 마련'),
    ('other', '기타'),
]

CURRENT_PRODUCTS=[
    ('savings_account', '적금'),
    ('fixed_deposit', '예금'),
    ('investment_fund', '투자 펀드'),
    ('retirement_account', '연금 계좌'),
    ('credit_card', '신용카드'),
    ('other', '기타'),
]

class Survey(models.Model):
    full_name = models.CharField(max_length=100)
    ages = models.CharField(max_length=5, choices=AGE_CHOICES)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    monthly_income = models.DecimalField(max_digits=10, decimal_places=2)
    additional_income = models.DecimalField(max_digits=10, decimal_places=2)
    monthly_expenses = models.DecimalField(max_digits=10, decimal_places=2)
    debt_amount = models.DecimalField(max_digits=10, decimal_places=2)
    financial_goals = models.CharField(max_length=20, choices=FINANCIAL_GOAL_CHOICES)
    risk_tolerance = models.CharField(max_length=10)  # 'low', 'medium', 'high'
    current_financial_products = models.CharField(max_length=20, choices=CURRENT_PRODUCTS)
    satisfaction_level = models.CharField(max_length=20)  # 'very_satisfied', 'satisfied', ...
    financial_advice_needed = models.BooleanField(default=False)
    # 다른 필드들도 추가...

    def __str__(self):
        return self.full_name

knu/mypolls/forms.py
from django import forms
from .models import Survey, AGE_CHOICES, CURRENT_PRODUCTS, FINANCIAL_GOAL_CHOICES, GENDER_CHOICES

class SurveyForm(forms.ModelForm):
    class Meta:
        model = Survey
        fields = '__all__'
        
    ages = forms.ChoiceField(
        label='나이',
        choices=AGE_CHOICES,
        widget=forms.RadioSelect,
    )


    gender = forms.ChoiceField(
        label='성별',
        choices=GENDER_CHOICES,
        widget=forms.RadioSelect,
    )

    monthly_income = forms.DecimalField(label='월 소득')
    additional_income = forms.DecimalField(label='기타 소득')

    # 지출 정보
    monthly_expenses = forms.DecimalField(label='월 지출')
    debt_amount = forms.DecimalField(label='현재 부채')

    # 금융 목표
    financial_goals = forms.ChoiceField(
        label='금융 목표',
        choices=FINANCIAL_GOAL_CHOICES,
        widget=forms.RadioSelect,
    )

    # 위험 허용 수준
    risk_tolerance = forms.ChoiceField(
        label='위험 허용 수준',
        choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음')],
    )

    current_financial_products = forms.ChoiceField(
        label='현재 보유 중인 금융 상품',
        choices=CURRENT_PRODUCTS,
        widget=forms.RadioSelect,
    )

    # 금융 상품 만족도
    satisfaction_level = forms.ChoiceField(
        label='현재 보유 중인 금융 상품에 대한 만족도',
        choices=[
            ('very_satisfied', '매우 만족함'),
            ('satisfied', '만족함'),
            ('neutral', '보통'),
            ('dissatisfied', '불만족함'),
            ('very_dissatisfied', '매우 불만족함'),
        ],
    )

    # 추가적인 금융 상담 희망 여부
    financial_advice_needed = forms.BooleanField(
        label='추가적인 금융 상담을 받고 싶으신가요?',
        required=False,
    )

knu/mypolls/views.py
# views.py
from django.shortcuts import render, redirect
from .forms import SurveyForm
from .models import Survey

def survey(request):
    if request.method == 'POST':
        form = SurveyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('mypolls:result')
    else:
        form = SurveyForm()

    return render(request, 'mypolls/survey.html', {'form': form})


def result(request):
    surveys = Survey.objects.all()
    return render(request, 'mypolls/result.html', {'surveys': surveys})

knu/mypolls/templates/mypolls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Survey{% endblock %}</title>
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

knu/mypolls/templates/mypolls/result.html
<!-- result.html -->

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Financial Survey</title>
    <link rel="stylesheet" href="{% static 'css/survey.css' %}">
</head>
<body>
<div id="survey-container" class="result-container">
    <h2 class="result-heading">Survey Results</h2>
    <ul class="result-list">
        {% for survey in surveys %}
            <li class="result-item">
                <p class="result-detail"><strong>성명:</strong> {{ survey.full_name }}</p>
                <p class="result-detail"><strong>나이:</strong> {{ survey.ages }}</p>
                <p class="result-detail"><strong>성별:</strong> {{ survey.gender }}</p>
                <p class="result-detail"><strong>월 소득:</strong> {{ survey.monthly_income }}</p>
                <p class="result-detail"><strong>기타 소득:</strong> {{ survey.additional_income }}</p>
                <p class="result-detail"><strong>월 지출:</strong> {{ survey.monthly_expenses }}</p>
                <p class="result-detail"><strong>현재 부채:</strong> {{ survey.debt_amount }}</p>
                <p class="result-detail"><strong>금융 목표:</strong> {{ survey.financial_goals }}</p>
                <p class="result-detail"><strong>위험 허용 수준:</strong> {{ survey.risk_tolerance }}</p>
                <p class="result-detail"><strong>현재 보유 중인 금융 상품:</strong> {{ survey.current_financial_products }}</p>
                <p class="result-detail"><strong>만족도:</strong> {{ survey.satisfaction_level }}</p>
                <p class="result-detail"><strong>추가적인 금융 상담 희망 여부:</strong> {{ survey.financial_advice_needed }}</p>
            </li>
        {% endfor %}
    </ul>
</div>

</body>
</html>

knu/mypolls/templates/mypolls/survey.html
<!-- survey.html -->

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Financial Survey</title>
    <link rel="stylesheet" href="{% static 'css/survey.css' %}">
</head>
<body>

<div id="survey-container">
<form method="post" action="{% url 'mypolls:survey' %}">
    {% csrf_token %}
    <div class="survey-field">
        <label for="id_full_name" class="survey-label">성명:</label>
        {{ form.full_name }}
    </div>
    
    <div class="survey-field">
        <label for="id_age" class="survey-label">나이:</label>
        {{ form.ages }}
        </div>

        <div class="survey-field">
            <label for="id_gender" class="survey-label">성별:</label>
            {{ form.gender }}
        </div>

        <div class="survey-field">
            <label for="id_monthly_income" class="survey-label">월 소득:</label>
            {{ form.monthly_income }}
        </div>

        <div class="survey-field">
            <label for="id_additional_income" class="survey-label">기타 소득:</label>
            {{ form.additional_income }}
        </div>

        <div class="survey-field">
            <label for="id_monthly_expenses" class="survey-label">월 지출:</label>
            {{ form.monthly_expenses }}
        </div>

        <div class="survey-field">
            <label for="id_debt_amount" class="survey-label">현재 부채:</label>
            {{ form.debt_amount }}
        </div>

        <div class="survey-field">
            <label for="id_financial_goals" class="survey-label">금융 목표:</label>
            {{ form.financial_goals }}
        </div>

        <div class="survey-field">
            <label for="id_risk_tolerance" class="survey-label">위험 허용 수준:</label>
            {{ form.risk_tolerance }}
        </div>

        <div class="survey-field">
            <label for="id_current_financial_products" class="survey-label">현재 보유 중인 금융 상품:</label>
            {{ form.current_financial_products }}
        </div>

        <div class="survey-field">
            <label for="id_satisfaction_level" class="survey-label">현재 보유 중인 금융 상품에 대한 만족도:</label>
            {{ form.satisfaction_level }}
        </div>

        <div class="survey-field">
            <label for="id_financial_advice_needed" class="survey-label">추가적인 금융 상담 희망 여부:</label>
            {{ form.financial_advice_needed }}
        </div>
        <button type="submit">Submit</button>
    </form>
</div>

</body>
</html>